# Generated by Django 2.1.7 on 2019-03-20 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pjts_name', models.CharField(max_length=200)),
                ('pjts_detail', models.CharField(max_length=400)),
                ('pjts_coins', models.IntegerField(default=500)),
                ('pjts_time', models.DateTimeField(auto_now_add=True)),
                ('pjts_nowcoins', models.IntegerField(default=0)),
                ('pjts_now', models.NullBooleanField(default=True)),
                ('pjts_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Users')),
            ],
        ),
    ]
