# Generated by Django 2.1.7 on 2019-04-21 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0004_users_bool'),
        ('projects', '0004_projects_pjts_bool'),
    ]

    operations = [
        migrations.CreateModel(
            name='blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Users')),
            ],
        ),
        migrations.CreateModel(
            name='investbill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iv_coins', models.IntegerField()),
                ('iv_ps', models.CharField(max_length=500)),
                ('iv_time', models.DateTimeField(auto_now_add=True)),
                ('iv_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Users')),
                ('iv_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
        ),
    ]
