# Generated by Django 2.1.7 on 2019-04-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='User',
        ),
        migrations.DeleteModel(
            name='blacklist',
        ),
    ]
