# Generated by Django 2.1.7 on 2019-04-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(default='buQYvwKqwE2m3Y8Vuoy79McXh68amDD7TaNS', max_length=100),
        ),
        migrations.AddField(
            model_name='users',
            name='private_key',
            field=models.CharField(default='b001f9ab8f65ef228f1270a29e23de0920fbaf22403412ccd2ed7115ac68b5611de45aad0eb2', max_length=200),
        ),
        migrations.AddField(
            model_name='users',
            name='public_key',
            field=models.CharField(default='privbxfPrswQWZ4YZQeFLrCviVvy8EkaBgPLNRR5EZzmVfUnhcSz2m3h', max_length=200),
        ),
    ]
