# Generated by Django 2.1.7 on 2019-04-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190406_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='bool',
            field=models.NullBooleanField(default=False),
        ),
    ]
