# Generated by Django 2.1.7 on 2019-04-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermana', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='Vl_Detail',
            new_name='Vl_detail',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='Vl_name',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
