# Generated by Django 2.1.7 on 2019-04-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermana', '0003_auto_20190427_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='Bl_User',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='Vl_User',
        ),
        migrations.DeleteModel(
            name='Blacklist',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
