# Generated by Django 2.1.7 on 2019-04-27 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermana', '0009_blacklist_volunteer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='Bl_User',
            new_name='Bl_user',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='Vl_Detail',
            new_name='Vl_detail',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='Vl_User',
            new_name='Vl_user',
        ),
    ]
